/*
 * monitor.c — PMU event setup, PEBS sample processing, OCR reading,
 *             per-object bandwidth estimation, ranking, and migration decisions.
 */
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
#include <sched.h>
#include <time.h>
#include <math.h>
#include <limits.h>
#include <stdatomic.h>
#include <sys/mman.h>
#include <sys/syscall.h>

#include "monitor.h"
#include "config.h"
#include "hook.h"
#include "log.h"
#include "obj_store.h"
#include "migrate.h"
#include "thread.h"
#include "perf_util.h"
#include "shm.h"
#include "regularity.h"
#include "swpf_cache.h"
#include "congest_ctrl.h"

monitor_ctx_t g_monitor;

/* ── Per-process self-opened OCR (multi-proc followers + leader) ── */
static int      g_self_ocr_shm_slot   = -1;   /* slot in shm->proc_ocr[] */

static int      g_self_fd_demand_data_rd = -1;
static int      g_self_fd_demand_rfo     = -1;
static int      g_self_fd_hw_data_pf     = -1;
static int      g_self_fd_hw_rfo_pf      = -1;
static uint64_t g_self_prev_demand_data_rd, g_self_prev_demand_rfo, g_self_prev_hw_data_pf, g_self_prev_hw_rfo_pf;
static uint64_t g_self_prev_en_demand_data_rd, g_self_prev_en_demand_rfo, g_self_prev_en_hw_data_pf, g_self_prev_en_hw_rfo_pf;
static uint64_t g_self_prev_ru_demand_data_rd, g_self_prev_ru_demand_rfo, g_self_prev_ru_hw_data_pf, g_self_prev_ru_hw_rfo_pf;

#define OCR_EVENT_CONFIG               0x012A

/* ── OCR events (per-task counting mode) ── */
#define OCR_DEMAND_DATA_RD_L3_MISS_CFG1 0x3FFFC00001ULL
#define OCR_DEMAND_RFO_L3_MISS_CFG1     0x3FFFC00002ULL
/* OCR mask 0x3FFFC04410 covers L3-miss data prefetches generated by
 * either HW prefetchers (L1/L2 data-side, with the original 0x410 bits)
 * or SW prefetch instructions (PREFETCHNTA/T0/T1/T2/W/WT1, the new 0x4000
 * bit). The counter still measures one unified "total data PF" magnitude;
 * the HW vs SW split is recovered downstream from MEM_INST_RETIRED.ALL_LOADS
 * PEBS samples. */
#define OCR_TOTAL_DATA_PF_L3_MISS_CFG1  0x3FFFC04410ULL
#define OCR_HW_RFO_PF_L3_MISS_CFG1      0x3FFFC00020ULL

/* ── iMC uncore setup (UNC_M_CAS_COUNT.WR / .RD, Sapphire Rapids) ── */
static int imc_type_base = -1;
static int imc_cpu_for_node[NUM_NODES];

/* ── PEBS sample layout ── */
/* Fields follow sample_type bit order: IP(0), TID(1), ADDR(3), CPU(7) */
struct pebs_sample {
    struct perf_event_header header;
    uint64_t ip;           /* PERF_SAMPLE_IP   (bit 0) */
    uint32_t pid, tid;     /* PERF_SAMPLE_TID  (bit 1) */
    uint64_t addr;         /* PERF_SAMPLE_ADDR (bit 3) */
    uint32_t cpu, res;     /* PERF_SAMPLE_CPU  (bit 7) */
};

/*
 * store_sample layout: same fields as pebs_sample, plus weight at the tail.
 * sample_type bits enabled: IP(0) | TID(1) | ADDR(3) | CPU(7) | WEIGHT(14).
 */
struct pebs_store_sample {
    struct perf_event_header header;
    uint64_t ip;
    uint32_t pid, tid;
    uint64_t addr;
    uint32_t cpu, res;
    uint64_t weight;
};

static void cleanup_pebs_events(void)
{
    for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
        if (g_monitor.pebs_mmap[cpu]) {
            munmap(g_monitor.pebs_mmap[cpu], g_monitor.pebs_mmap_size);
            g_monitor.pebs_mmap[cpu] = NULL;
        }
        if (g_monitor.pebs_fd[cpu] >= 0) {
            close(g_monitor.pebs_fd[cpu]);
            g_monitor.pebs_fd[cpu] = -1;
        }
    }
}

static void cleanup_pebs_store_events(void)
{
    for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
        if (g_monitor.pebs_store_mmap[cpu]) {
            munmap(g_monitor.pebs_store_mmap[cpu], g_monitor.pebs_mmap_size);
            g_monitor.pebs_store_mmap[cpu] = NULL;
        }
        if (g_monitor.pebs_store_fd[cpu] >= 0) {
            close(g_monitor.pebs_store_fd[cpu]);
            g_monitor.pebs_store_fd[cpu] = -1;
        }
    }
}

static void cleanup_ocr_events(void)
{
    for (int i = 0; i < g_monitor.ocr_proc_count; i++) {
        if (g_monitor.ocr_procs[i].fd_demand_data_rd >= 0) {
            close(g_monitor.ocr_procs[i].fd_demand_data_rd);
            g_monitor.ocr_procs[i].fd_demand_data_rd = -1;
        }
        if (g_monitor.ocr_procs[i].fd_demand_rfo >= 0) {
            close(g_monitor.ocr_procs[i].fd_demand_rfo);
            g_monitor.ocr_procs[i].fd_demand_rfo = -1;
        }
        if (g_monitor.ocr_procs[i].fd_hw_data_pf >= 0) {
            close(g_monitor.ocr_procs[i].fd_hw_data_pf);
            g_monitor.ocr_procs[i].fd_hw_data_pf = -1;
        }
        if (g_monitor.ocr_procs[i].fd_hw_rfo_pf >= 0) {
            close(g_monitor.ocr_procs[i].fd_hw_rfo_pf);
            g_monitor.ocr_procs[i].fd_hw_rfo_pf = -1;
        }
    }
    g_monitor.ocr_proc_count = 0;
}

static void cleanup_imc_events(void)
{
    for (int node = 0; node < NUM_NODES; node++) {
        for (int ch = 0; ch < NUM_IMC_CHANNELS; ch++) {
            if (g_monitor.imc_wr_fds[node][ch] >= 0) {
                close(g_monitor.imc_wr_fds[node][ch]);
                g_monitor.imc_wr_fds[node][ch] = -1;
            }
            if (g_monitor.imc_rd_fds[node][ch] >= 0) {
                close(g_monitor.imc_rd_fds[node][ch]);
                g_monitor.imc_rd_fds[node][ch] = -1;
            }
        }
    }
}

static void init_ocr_attr(struct perf_event_attr *attr, uint64_t config1,
                          bool start_disabled)
{
    memset(attr, 0, sizeof(*attr));
    attr->type = PERF_TYPE_RAW;
    attr->size = sizeof(*attr);
    attr->config = OCR_EVENT_CONFIG;
    attr->config1 = config1;
    attr->sample_type = PERF_SAMPLE_IDENTIFIER;
    attr->read_format = PERF_FORMAT_TOTAL_TIME_ENABLED |
                        PERF_FORMAT_TOTAL_TIME_RUNNING;
    attr->disabled = start_disabled ? 1 : 0;
    attr->exclude_kernel = 1;
    attr->inherit = 1;
}

/* ── PMU event setup ── */

static int setup_pebs_events(void)
{
    g_monitor.pebs_mmap_size = (RING_BUFFER_PAGES + 1) * TM_PAGE_SIZE;

    /* Only monitor Node 0 CPUs — workloads are pinned there */
    for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
        struct perf_event_attr attr;
        memset(&attr, 0, sizeof(attr));
        attr.type           = PERF_TYPE_RAW;
        attr.size           = sizeof(attr);
        attr.config         = 0x20D1;  /* MEM_LOAD_RETIRED.L3_MISS */
        attr.sample_period  = g_config.pebs_period;
        attr.sample_type    = PERF_SAMPLE_IP | PERF_SAMPLE_ADDR |
                              PERF_SAMPLE_CPU | PERF_SAMPLE_TID;
        attr.read_format    = PERF_FORMAT_TOTAL_TIME_ENABLED |
                              PERF_FORMAT_TOTAL_TIME_RUNNING;
        attr.precise_ip     = 3;
        attr.disabled       = 1;
        attr.exclude_kernel = 1;
        attr.exclude_hv     = 1;
        attr.mmap           = 1;

        int fd = sys_perf_event_open(&attr, -1, cpu, -1, 0);
        if (fd < 0) {
            TM_ERR("Failed to open PEBS event on CPU %d: %s", cpu, strerror(errno));
            cleanup_pebs_events();
            return -1;
        }

        /* mmap ring buffer */
        void *base = mmap(NULL, g_monitor.pebs_mmap_size,
                          PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
        if (base == MAP_FAILED) {
            TM_ERR("Failed to mmap PEBS ring buffer on CPU %d: %s",
                   cpu, strerror(errno));
            close(fd);
            cleanup_pebs_events();
            return -1;
        }

        g_monitor.pebs_fd[cpu] = fd;
        g_monitor.pebs_mmap[cpu] = (struct perf_event_mmap_page *)base;
    }

    TM_DBG("PEBS events opened on CPUs 0-%d", NUM_CPUS_PER_NODE - 1);
    return 0;
}

static int setup_pebs_store_events(void)
{
    g_monitor.pebs_mmap_size = (RING_BUFFER_PAGES + 1) * TM_PAGE_SIZE;

    for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
        struct perf_event_attr attr;
        memset(&attr, 0, sizeof(attr));
        attr.type           = PERF_TYPE_RAW;
        attr.size           = sizeof(attr);
        /* MEM_TRANS_RETIRED.STORE_SAMPLE: EventCode=0xcd, UMask=0x02 */
        attr.config         = (0x02ULL << 8) | 0xcd;
        attr.sample_period  = g_config.store_period;
        attr.sample_type    = PERF_SAMPLE_IP   | PERF_SAMPLE_TID  |
                              PERF_SAMPLE_ADDR | PERF_SAMPLE_CPU  |
                              PERF_SAMPLE_WEIGHT;
        attr.read_format    = PERF_FORMAT_TOTAL_TIME_ENABLED |
                              PERF_FORMAT_TOTAL_TIME_RUNNING;
        attr.precise_ip     = 3;
        attr.disabled       = 1;
        attr.exclude_kernel = 1;
        attr.exclude_hv     = 1;
        attr.mmap           = 1;

        int fd = sys_perf_event_open(&attr, -1, cpu, -1, 0);
        if (fd < 0) {
            TM_ERR("Failed to open store PEBS on CPU %d: %s",
                   cpu, strerror(errno));
            cleanup_pebs_store_events();
            return -1;
        }
        void *base = mmap(NULL, g_monitor.pebs_mmap_size,
                          PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
        if (base == MAP_FAILED) {
            TM_ERR("Failed to mmap store PEBS on CPU %d: %s",
                   cpu, strerror(errno));
            close(fd);
            cleanup_pebs_store_events();
            return -1;
        }
        g_monitor.pebs_store_fd[cpu]   = fd;
        g_monitor.pebs_store_mmap[cpu] = (struct perf_event_mmap_page *)base;
    }
    TM_DBG("Store PEBS events opened on CPUs 0-%d", NUM_CPUS_PER_NODE - 1);
    return 0;
}

static void cleanup_pebs_allload_events(void)
{
    for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
        if (g_monitor.pebs_allload_mmap[cpu]) {
            munmap(g_monitor.pebs_allload_mmap[cpu], g_monitor.pebs_mmap_size);
            g_monitor.pebs_allload_mmap[cpu] = NULL;
        }
        if (g_monitor.pebs_allload_fd[cpu] >= 0) {
            close(g_monitor.pebs_allload_fd[cpu]);
            g_monitor.pebs_allload_fd[cpu] = -1;
        }
    }
}

static int setup_pebs_allload_events(void)
{
    g_monitor.pebs_mmap_size = (RING_BUFFER_PAGES + 1) * TM_PAGE_SIZE;
    for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
        struct perf_event_attr attr;
        memset(&attr, 0, sizeof(attr));
        attr.type           = PERF_TYPE_RAW;
        attr.size           = sizeof(attr);
        /* MEM_INST_RETIRED.ALL_LOADS: EventCode=0xD0 UMask=0x81.
         * Counts retired load uops including PREFETCHNTA/T0/T1/T2/W/WT1. */
        attr.config         = (0x81ULL << 8) | 0xD0;
        attr.sample_period  = g_config.allload_period;
        attr.sample_type    = PERF_SAMPLE_IP | PERF_SAMPLE_TID |
                              PERF_SAMPLE_ADDR | PERF_SAMPLE_CPU;
        attr.read_format    = PERF_FORMAT_TOTAL_TIME_ENABLED |
                              PERF_FORMAT_TOTAL_TIME_RUNNING;
        attr.precise_ip     = 3;
        attr.disabled       = 1;
        attr.exclude_kernel = 1;
        attr.exclude_hv     = 1;
        attr.mmap           = 1;

        int fd = sys_perf_event_open(&attr, -1, cpu, -1, 0);
        if (fd < 0) {
            TM_ERR("Failed to open allload PEBS on CPU %d: %s",
                   cpu, strerror(errno));
            cleanup_pebs_allload_events();
            return -1;
        }
        void *base = mmap(NULL, g_monitor.pebs_mmap_size,
                          PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
        if (base == MAP_FAILED) {
            TM_ERR("Failed to mmap allload PEBS on CPU %d: %s",
                   cpu, strerror(errno));
            close(fd);
            cleanup_pebs_allload_events();
            return -1;
        }
        g_monitor.pebs_allload_fd[cpu]   = fd;
        g_monitor.pebs_allload_mmap[cpu] = (struct perf_event_mmap_page *)base;
    }
    TM_DBG("ALL_LOADS PEBS opened on CPUs 0-%d", NUM_CPUS_PER_NODE - 1);
    return 0;
}

static int open_ocr_fd(pid_t pid, uint64_t config1, bool start_disabled)
{
    struct perf_event_attr a;
    init_ocr_attr(&a, config1, start_disabled);
    int fd = sys_perf_event_open(&a, pid, -1, -1, 0);
    if (fd < 0)
        TM_ERR("open_ocr_fd(pid=%d cfg1=%#lx): %s",
               (int)pid, (unsigned long)config1, strerror(errno));
    return fd;
}

/*
 * Open 4 per-process OCR counting events for the given PID.
 * pid=0 means "self" (the calling process).
 * Returns 0 on success, -1 on failure.
 */
static int setup_ocr_for_pid(pid_t pid)
{
    if (g_monitor.ocr_proc_count >= MAX_PROCS) {
        TM_ERR("OCR proc table full (%d)", MAX_PROCS);
        return -1;
    }

    proc_ocr_t *po = &g_monitor.ocr_procs[g_monitor.ocr_proc_count];
    memset(po, 0, sizeof(*po));
    po->pid = pid ? pid : getpid();
    po->fd_demand_data_rd = -1;
    po->fd_demand_rfo     = -1;
    po->fd_hw_data_pf     = -1;
    po->fd_hw_rfo_pf      = -1;

    po->fd_demand_data_rd = open_ocr_fd(pid, OCR_DEMAND_DATA_RD_L3_MISS_CFG1, true);
    po->fd_demand_rfo     = open_ocr_fd(pid, OCR_DEMAND_RFO_L3_MISS_CFG1, true);
    po->fd_hw_data_pf     = open_ocr_fd(pid, OCR_TOTAL_DATA_PF_L3_MISS_CFG1, true);
    po->fd_hw_rfo_pf      = open_ocr_fd(pid, OCR_HW_RFO_PF_L3_MISS_CFG1,  true);
    if (po->fd_demand_data_rd < 0 || po->fd_demand_rfo < 0 ||
        po->fd_hw_data_pf < 0 || po->fd_hw_rfo_pf < 0) {
        if (po->fd_demand_data_rd >= 0) close(po->fd_demand_data_rd);
        if (po->fd_demand_rfo     >= 0) close(po->fd_demand_rfo);
        if (po->fd_hw_data_pf     >= 0) close(po->fd_hw_data_pf);
        if (po->fd_hw_rfo_pf      >= 0) close(po->fd_hw_rfo_pf);
        return -1;
    }

    struct perf_read_scaled s;
    s = perf_read_count_scaled(po->fd_demand_data_rd);
    po->prev_demand_data_rd    = s.value;
    po->prev_en_demand_data_rd = s.time_enabled;
    po->prev_ru_demand_data_rd = s.time_running;
    s = perf_read_count_scaled(po->fd_demand_rfo);
    po->prev_demand_rfo    = s.value;
    po->prev_en_demand_rfo = s.time_enabled;
    po->prev_ru_demand_rfo = s.time_running;
    s = perf_read_count_scaled(po->fd_hw_data_pf);
    po->prev_hw_data_pf    = s.value;
    po->prev_en_hw_data_pf = s.time_enabled;
    po->prev_ru_hw_data_pf = s.time_running;
    s = perf_read_count_scaled(po->fd_hw_rfo_pf);
    po->prev_hw_rfo_pf     = s.value;
    po->prev_en_hw_rfo_pf  = s.time_enabled;
    po->prev_ru_hw_rfo_pf  = s.time_running;

    g_monitor.ocr_proc_count++;
    TM_DBG("OCR events opened for pid %d (slot %d)",
           (int)po->pid, g_monitor.ocr_proc_count - 1);
    return 0;
}

static int setup_ocr_events(void)
{
    if (g_config.multi_proc) {
        /*
         * Multi-process: each process opens OCR for itself via
         * ocr_self_init() (called from hook_main.c before thread creation).
         * The leader only needs a proc_ocr_t entry (fds=-1) for itself
         * so that its own OCR values (read from shm) can participate
         * in per-object BW computation via the same code path.
         *
         * We still register a proc_ocr_t slot for the leader here, but
         * with fds=-1.  The leader's actual OCR data comes from
         * ocr_self_read_to_shm() → shm → collect_follower_ocr().
         */
        proc_ocr_t *po = &g_monitor.ocr_procs[0];
        memset(po, 0, sizeof(*po));
        po->pid = getpid();
        po->fd_demand_data_rd = -1;
        po->fd_demand_rfo     = -1;
        po->fd_hw_data_pf     = -1;
        po->fd_hw_rfo_pf      = -1;
        g_monitor.ocr_proc_count = 1;
        return 0;
    }

    /* Single-process: open OCR events directly (leader reads them) */
    if (setup_ocr_for_pid(0) != 0)
        return -1;

    return 0;
}

/*
 * Multi-process: scan process registry for PIDs that don't have a
 * proc_ocr_t entry yet.  In multi-proc mode we don't open per-PID
 * OCR fds from the leader (inherit won't cover pre-existing threads).
 * Instead, each process opens its own OCR via ocr_self_init() and
 * reports through shared memory.  Here we just register placeholder
 * proc_ocr_t entries (fds=-1) so the BW computation loop can iterate
 * all processes uniformly.
 */
static void check_new_procs_ocr(void)
{
    if (!g_config.multi_proc || !g_shm) return;

    int n = atomic_load_explicit(&g_shm->proc_count, memory_order_acquire);
    for (int i = 0; i < n; i++) {
        pid_t p = g_shm->proc_pids[i];
        if (p <= 0) continue;

        /* Check if we already track this PID */
        bool found = false;
        for (int j = 0; j < g_monitor.ocr_proc_count; j++) {
            if (g_monitor.ocr_procs[j].pid == p) {
                found = true;
                break;
            }
        }
        if (!found && g_monitor.ocr_proc_count < MAX_PROCS) {
            proc_ocr_t *po = &g_monitor.ocr_procs[g_monitor.ocr_proc_count++];
            memset(po, 0, sizeof(*po));
            po->pid = p;
            po->fd_demand_data_rd = -1;
            po->fd_demand_rfo     = -1;
            po->fd_hw_data_pf     = -1;
            po->fd_hw_rfo_pf      = -1;
            TM_INFO("Registered OCR tracking for process pid %d", (int)p);
        }
    }
}

/*
 * Open OCR counting events for this process (pid=0) and claim a shared
 * memory slot.  Must be called during init, BEFORE any application threads
 * are created so that inherit=1 covers them all.
 */
int ocr_self_init(void)
{
    g_self_fd_demand_data_rd = open_ocr_fd(0, OCR_DEMAND_DATA_RD_L3_MISS_CFG1, false);
    g_self_fd_demand_rfo     = open_ocr_fd(0, OCR_DEMAND_RFO_L3_MISS_CFG1, false);
    g_self_fd_hw_data_pf     = open_ocr_fd(0, OCR_TOTAL_DATA_PF_L3_MISS_CFG1, false);
    g_self_fd_hw_rfo_pf      = open_ocr_fd(0, OCR_HW_RFO_PF_L3_MISS_CFG1,  false);
    if (g_self_fd_demand_data_rd < 0 || g_self_fd_demand_rfo < 0 ||
        g_self_fd_hw_data_pf < 0 || g_self_fd_hw_rfo_pf < 0) {
        if (g_self_fd_demand_data_rd >= 0) { close(g_self_fd_demand_data_rd); g_self_fd_demand_data_rd = -1; }
        if (g_self_fd_demand_rfo     >= 0) { close(g_self_fd_demand_rfo);     g_self_fd_demand_rfo     = -1; }
        if (g_self_fd_hw_data_pf     >= 0) { close(g_self_fd_hw_data_pf);     g_self_fd_hw_data_pf     = -1; }
        if (g_self_fd_hw_rfo_pf      >= 0) { close(g_self_fd_hw_rfo_pf);      g_self_fd_hw_rfo_pf      = -1; }
        TM_ERR("ocr_self_init: failed to open 4-event OCR fds");
        return -1;
    }

    struct perf_read_scaled _s;
    _s = perf_read_count_scaled(g_self_fd_demand_data_rd);
    g_self_prev_demand_data_rd    = _s.value;
    g_self_prev_en_demand_data_rd = _s.time_enabled;
    g_self_prev_ru_demand_data_rd = _s.time_running;
    _s = perf_read_count_scaled(g_self_fd_demand_rfo);
    g_self_prev_demand_rfo    = _s.value;
    g_self_prev_en_demand_rfo = _s.time_enabled;
    g_self_prev_ru_demand_rfo = _s.time_running;
    _s = perf_read_count_scaled(g_self_fd_hw_data_pf);
    g_self_prev_hw_data_pf    = _s.value;
    g_self_prev_en_hw_data_pf = _s.time_enabled;
    g_self_prev_ru_hw_data_pf = _s.time_running;
    _s = perf_read_count_scaled(g_self_fd_hw_rfo_pf);
    g_self_prev_hw_rfo_pf     = _s.value;
    g_self_prev_en_hw_rfo_pf  = _s.time_enabled;
    g_self_prev_ru_hw_rfo_pf  = _s.time_running;

    /* Claim a slot in shared memory */
    if (g_config.multi_proc && g_shm) {
        g_self_ocr_shm_slot = shm_claim_ocr_slot(getpid());
        if (g_self_ocr_shm_slot < 0)
            TM_ERR("ocr_self_init: no shm slot available");
    }

    TM_DBG("OCR self-init: pid=%d shm_slot=%d", getpid(), g_self_ocr_shm_slot);
    return 0;
}

void ocr_self_cleanup(void)
{
    if (g_self_fd_demand_data_rd >= 0) { close(g_self_fd_demand_data_rd); g_self_fd_demand_data_rd = -1; }
    if (g_self_fd_demand_rfo     >= 0) { close(g_self_fd_demand_rfo);     g_self_fd_demand_rfo     = -1; }
    if (g_self_fd_hw_data_pf     >= 0) { close(g_self_fd_hw_data_pf);     g_self_fd_hw_data_pf     = -1; }
    if (g_self_fd_hw_rfo_pf      >= 0) { close(g_self_fd_hw_rfo_pf);      g_self_fd_hw_rfo_pf      = -1; }
}

/*
 * Read this process's OCR counters and accumulate deltas into the
 * shared-memory slot.  Called periodically by the follower thread
 * and also by the leader for its own slot.
 */
static void ocr_self_read_to_shm(void)
{
    if (g_self_fd_demand_rfo < 0 || g_self_ocr_shm_slot < 0) return;

    /* 4-event accumulators into shm */
#define SELF_READ_SCALE_SHM(FD, PREV_V, PREV_EN, PREV_RU,                  \
                             SHM_DELTA, SHM_EN, SHM_RU) do {               \
    if ((FD) >= 0) {                                                        \
        struct perf_read_scaled _s = perf_read_count_scaled(FD);            \
        uint64_t _dv = _s.value        - (PREV_V);                          \
        uint64_t _de = _s.time_enabled - (PREV_EN);                         \
        uint64_t _dr = _s.time_running - (PREV_RU);                         \
        if (_dr > 0) _dv = _dv * _de / _dr;                                 \
        (PREV_V)  = _s.value;                                               \
        (PREV_EN) = _s.time_enabled;                                        \
        (PREV_RU) = _s.time_running;                                        \
        atomic_fetch_add_explicit(&g_shm->proc_ocr[g_self_ocr_shm_slot].SHM_DELTA, \
                                  _dv, memory_order_relaxed);               \
        atomic_fetch_add_explicit(&g_shm->proc_ocr[g_self_ocr_shm_slot].SHM_EN,    \
                                  _de, memory_order_relaxed);               \
        atomic_fetch_add_explicit(&g_shm->proc_ocr[g_self_ocr_shm_slot].SHM_RU,    \
                                  _dr, memory_order_relaxed);               \
    }                                                                       \
} while (0)

    SELF_READ_SCALE_SHM(g_self_fd_demand_data_rd,
                        g_self_prev_demand_data_rd,
                        g_self_prev_en_demand_data_rd,
                        g_self_prev_ru_demand_data_rd,
                        delta_demand_data_rd, en_demand_data_rd, ru_demand_data_rd);
    SELF_READ_SCALE_SHM(g_self_fd_demand_rfo,
                        g_self_prev_demand_rfo,
                        g_self_prev_en_demand_rfo,
                        g_self_prev_ru_demand_rfo,
                        delta_demand_rfo, en_demand_rfo, ru_demand_rfo);
    SELF_READ_SCALE_SHM(g_self_fd_hw_data_pf,
                        g_self_prev_hw_data_pf,
                        g_self_prev_en_hw_data_pf,
                        g_self_prev_ru_hw_data_pf,
                        delta_hw_data_pf, en_hw_data_pf, ru_hw_data_pf);
    SELF_READ_SCALE_SHM(g_self_fd_hw_rfo_pf,
                        g_self_prev_hw_rfo_pf,
                        g_self_prev_en_hw_rfo_pf,
                        g_self_prev_ru_hw_rfo_pf,
                        delta_hw_rfo_pf, en_hw_rfo_pf, ru_hw_rfo_pf);

#undef SELF_READ_SCALE_SHM
}

/* ── Event enable/disable ── */

void monitor_enable_events(void)
{
    for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
        perf_enable(g_monitor.pebs_fd[cpu]);
        if (g_monitor.pebs_store_fd[cpu] >= 0)
            perf_enable(g_monitor.pebs_store_fd[cpu]);
        if (g_monitor.pebs_allload_fd[cpu] >= 0)
            perf_enable(g_monitor.pebs_allload_fd[cpu]);
    }
    for (int i = 0; i < g_monitor.ocr_proc_count; i++) {
        if (g_monitor.ocr_procs[i].fd_demand_data_rd >= 0) perf_enable(g_monitor.ocr_procs[i].fd_demand_data_rd);
        if (g_monitor.ocr_procs[i].fd_demand_rfo     >= 0) perf_enable(g_monitor.ocr_procs[i].fd_demand_rfo);
        if (g_monitor.ocr_procs[i].fd_hw_data_pf     >= 0) perf_enable(g_monitor.ocr_procs[i].fd_hw_data_pf);
        if (g_monitor.ocr_procs[i].fd_hw_rfo_pf      >= 0) perf_enable(g_monitor.ocr_procs[i].fd_hw_rfo_pf);
    }
    for (int node = 0; node < NUM_NODES; node++)
        for (int ch = 0; ch < NUM_IMC_CHANNELS; ch++) {
            if (g_monitor.imc_wr_fds[node][ch] >= 0)
                perf_enable(g_monitor.imc_wr_fds[node][ch]);
            if (g_monitor.imc_rd_fds[node][ch] >= 0)
                perf_enable(g_monitor.imc_rd_fds[node][ch]);
        }
}

void monitor_disable_events(void)
{
    for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
        if (g_monitor.pebs_fd[cpu] >= 0) perf_disable(g_monitor.pebs_fd[cpu]);
        if (g_monitor.pebs_store_fd[cpu] >= 0) perf_disable(g_monitor.pebs_store_fd[cpu]);
        if (g_monitor.pebs_allload_fd[cpu] >= 0) perf_disable(g_monitor.pebs_allload_fd[cpu]);
    }
    for (int i = 0; i < g_monitor.ocr_proc_count; i++) {
        if (g_monitor.ocr_procs[i].fd_demand_data_rd >= 0) perf_disable(g_monitor.ocr_procs[i].fd_demand_data_rd);
        if (g_monitor.ocr_procs[i].fd_demand_rfo     >= 0) perf_disable(g_monitor.ocr_procs[i].fd_demand_rfo);
        if (g_monitor.ocr_procs[i].fd_hw_data_pf     >= 0) perf_disable(g_monitor.ocr_procs[i].fd_hw_data_pf);
        if (g_monitor.ocr_procs[i].fd_hw_rfo_pf      >= 0) perf_disable(g_monitor.ocr_procs[i].fd_hw_rfo_pf);
    }
    for (int node = 0; node < NUM_NODES; node++)
        for (int ch = 0; ch < NUM_IMC_CHANNELS; ch++) {
            if (g_monitor.imc_wr_fds[node][ch] >= 0)
                perf_disable(g_monitor.imc_wr_fds[node][ch]);
            if (g_monitor.imc_rd_fds[node][ch] >= 0)
                perf_disable(g_monitor.imc_rd_fds[node][ch]);
        }
}

/* ── PEBS ring buffer processing ── */

static void drain_pebs_buffer(int cpu)
{
    struct perf_event_mmap_page *page = g_monitor.pebs_mmap[cpu];
    if (!page) return;

    uint64_t head = rb_read_head(page);
    uint64_t tail = page->data_tail;
    if (head == tail) return;

    char *data = (char *)page + TM_PAGE_SIZE;
    size_t mask = RING_BUFFER_PAGES * TM_PAGE_SIZE - 1;

    while (tail < head) {
        struct perf_event_header *hdr =
            (struct perf_event_header *)(data + (tail & mask));

        if (hdr->type == PERF_RECORD_SAMPLE) {
            /* Parse sample — need to handle wrap-around */
            struct pebs_sample sample;
            size_t offset = tail & mask;
            size_t avail = (RING_BUFFER_PAGES * TM_PAGE_SIZE) - offset;

            if (avail >= hdr->size) {
                memcpy(&sample, hdr, sizeof(sample));
            } else {
                /* Sample straddles ring buffer boundary */
                memcpy(&sample, hdr, avail);
                memcpy((char *)&sample + avail, data, sizeof(sample) - avail);
            }

            /* Attribute sample to object */
            mem_object_t *obj = obj_store_lookup(sample.pid, sample.addr);
            if (obj) {
                obj->load_sample_count++;
                g_monitor.samples_collected++;
            } else {
                g_monitor.samples_unmatched++;
            }
        } else if (hdr->type == PERF_RECORD_LOST) {
            struct {
                struct perf_event_header header;
                uint64_t id;
                uint64_t lost;
            } *lost = (void *)hdr;
            g_monitor.samples_lost += lost->lost;
        }

        tail += hdr->size;
    }

    rb_write_tail(page, tail);
}

static void drain_pebs_store_buffer(int cpu)
{
    struct perf_event_mmap_page *page = g_monitor.pebs_store_mmap[cpu];
    if (!page) return;

    uint64_t head = rb_read_head(page);
    uint64_t tail = page->data_tail;
    if (head == tail) return;

    char *data = (char *)page + TM_PAGE_SIZE;
    size_t mask = RING_BUFFER_PAGES * TM_PAGE_SIZE - 1;

    while (tail < head) {
        struct perf_event_header *hdr =
            (struct perf_event_header *)(data + (tail & mask));

        if (hdr->type == PERF_RECORD_SAMPLE) {
            struct pebs_store_sample sample;
            size_t offset = tail & mask;
            size_t avail = (RING_BUFFER_PAGES * TM_PAGE_SIZE) - offset;
            if (avail >= hdr->size) {
                memcpy(&sample, hdr, sizeof(sample));
            } else {
                memcpy(&sample, hdr, avail);
                memcpy((char *)&sample + avail, data, sizeof(sample) - avail);
            }

            mem_object_t *obj = obj_store_lookup(sample.pid, sample.addr);
            if (obj) {
                obj->store_sample_count++;
                obj->store_lat_sum += sample.weight;
                uintptr_t page_addr = sample.addr >> TM_PAGE_SHIFT;
                if (obj->last_store_addr != 0) {
                    int64_t d = (int64_t)page_addr - (int64_t)obj->last_store_addr;
                    obj->store_stride_bins[linear_stride_bin(d, obj->size)]++;
                }
                obj->last_store_addr = page_addr;
                g_monitor.store_samples_collected++;
            } else {
                g_monitor.store_samples_unmatched++;
            }
        } else if (hdr->type == PERF_RECORD_LOST) {
            struct {
                struct perf_event_header header;
                uint64_t id;
                uint64_t lost;
            } *lost = (void *)hdr;
            g_monitor.store_samples_lost += lost->lost;
        }

        tail += hdr->size;
    }

    rb_write_tail(page, tail);
}

static void drain_pebs_allload_buffer(int cpu)
{
    struct perf_event_mmap_page *page = g_monitor.pebs_allload_mmap[cpu];
    if (!page) return;

    uint64_t head = rb_read_head(page);
    uint64_t tail = page->data_tail;
    if (head == tail) return;

    char *data = (char *)page + TM_PAGE_SIZE;
    size_t mask = RING_BUFFER_PAGES * TM_PAGE_SIZE - 1;

    while (tail < head) {
        struct perf_event_header *hdr =
            (struct perf_event_header *)(data + (tail & mask));

        if (hdr->type == PERF_RECORD_SAMPLE) {
            struct pebs_sample sample;
            size_t offset = tail & mask;
            size_t avail  = (RING_BUFFER_PAGES * TM_PAGE_SIZE) - offset;
            if (avail >= hdr->size) {
                memcpy(&sample, hdr, sizeof(sample));
            } else {
                memcpy(&sample, hdr, avail);
                memcpy((char *)&sample + avail, data, sizeof(sample) - avail);
            }

            mem_object_t *obj = obj_store_lookup(sample.pid, sample.addr);
            if (obj) {
                obj->allload_sample_count++;
                g_monitor.allload_samples_collected++;
                /* Classify by reading the opcode at sample.ip */
                if (swpf_is_prefetch((pid_t)sample.pid, sample.ip)) {
                    obj->pf_sample_count++;
                    g_monitor.allload_samples_pf++;
                } else {
                    uintptr_t page_addr = sample.addr >> TM_PAGE_SHIFT;
                    if (obj->last_load_addr != 0) {
                        int64_t d = (int64_t)page_addr -
                                    (int64_t)obj->last_load_addr;
                        obj->load_stride_bins[linear_stride_bin(d, obj->size)]++;
                    }
                    obj->last_load_addr = page_addr;
                }
            } else {
                g_monitor.allload_samples_unmatched++;
            }
        } else if (hdr->type == PERF_RECORD_LOST) {
            struct {
                struct perf_event_header header;
                uint64_t id;
                uint64_t lost;
            } *lost = (void *)hdr;
            g_monitor.allload_samples_lost += lost->lost;
        }

        tail += hdr->size;
    }
    rb_write_tail(page, tail);
}

/* ── OCR counter reading ── */

static void read_ocr_counters(void)
{
    for (int i = 0; i < g_monitor.ocr_proc_count; i++) {
        proc_ocr_t *po = &g_monitor.ocr_procs[i];

        /* In multi-proc mode, entries with fds=-1 get their OCR data
         * from shared memory (see collect_shm_ocr below), skip here. */
        if (po->fd_demand_data_rd < 0) continue;

#define READ_SCALE_ACCUM(FD, PREV_V, PREV_EN, PREV_RU, EPOCH) do {          \
    if ((FD) >= 0) {                                                        \
        struct perf_read_scaled _s = perf_read_count_scaled(FD);            \
        uint64_t _dv = _s.value        - (PREV_V);                          \
        uint64_t _de = _s.time_enabled - (PREV_EN);                         \
        uint64_t _dr = _s.time_running - (PREV_RU);                         \
        if (_dr > 0) _dv = _dv * _de / _dr;                                 \
        (EPOCH) += _dv;                                                     \
        (PREV_V)  = _s.value;                                               \
        (PREV_EN) = _s.time_enabled;                                        \
        (PREV_RU) = _s.time_running;                                        \
    }                                                                       \
} while (0)

        READ_SCALE_ACCUM(po->fd_demand_data_rd, po->prev_demand_data_rd,
                         po->prev_en_demand_data_rd, po->prev_ru_demand_data_rd,
                         po->epoch_demand_data_rd);
        READ_SCALE_ACCUM(po->fd_demand_rfo,     po->prev_demand_rfo,
                         po->prev_en_demand_rfo, po->prev_ru_demand_rfo,
                         po->epoch_demand_rfo);
        READ_SCALE_ACCUM(po->fd_hw_data_pf,     po->prev_hw_data_pf,
                         po->prev_en_hw_data_pf, po->prev_ru_hw_data_pf,
                         po->epoch_hw_data_pf);
        READ_SCALE_ACCUM(po->fd_hw_rfo_pf,      po->prev_hw_rfo_pf,
                         po->prev_en_hw_rfo_pf,  po->prev_ru_hw_rfo_pf,
                         po->epoch_hw_rfo_pf);

#undef READ_SCALE_ACCUM
    }
}

/*
 * Multi-process: collect each process's OCR epoch data from shared memory
 * into the corresponding proc_ocr_t entry.  Uses atomic_exchange to read
 * and zero in one step, so follower accumulations after this point count
 * towards the next epoch.
 */
static void collect_shm_ocr(void)
{
    if (!g_config.multi_proc || !g_shm) return;

    for (int i = 0; i < g_monitor.ocr_proc_count; i++) {
        proc_ocr_t *po = &g_monitor.ocr_procs[i];
        int slot = shm_find_ocr_slot(po->pid);
        if (slot < 0) continue;

        po->epoch_demand_data_rd = atomic_exchange_explicit(
            &g_shm->proc_ocr[slot].delta_demand_data_rd, 0, memory_order_acq_rel);
        (void)atomic_exchange_explicit(&g_shm->proc_ocr[slot].en_demand_data_rd, 0, memory_order_acq_rel);
        (void)atomic_exchange_explicit(&g_shm->proc_ocr[slot].ru_demand_data_rd, 0, memory_order_acq_rel);
        po->epoch_demand_rfo     = atomic_exchange_explicit(
            &g_shm->proc_ocr[slot].delta_demand_rfo,     0, memory_order_acq_rel);
        (void)atomic_exchange_explicit(&g_shm->proc_ocr[slot].en_demand_rfo, 0, memory_order_acq_rel);
        (void)atomic_exchange_explicit(&g_shm->proc_ocr[slot].ru_demand_rfo, 0, memory_order_acq_rel);
        po->epoch_hw_data_pf     = atomic_exchange_explicit(
            &g_shm->proc_ocr[slot].delta_hw_data_pf,     0, memory_order_acq_rel);
        (void)atomic_exchange_explicit(&g_shm->proc_ocr[slot].en_hw_data_pf, 0, memory_order_acq_rel);
        (void)atomic_exchange_explicit(&g_shm->proc_ocr[slot].ru_hw_data_pf, 0, memory_order_acq_rel);
        po->epoch_hw_rfo_pf      = atomic_exchange_explicit(
            &g_shm->proc_ocr[slot].delta_hw_rfo_pf,      0, memory_order_acq_rel);
        (void)atomic_exchange_explicit(&g_shm->proc_ocr[slot].en_hw_rfo_pf, 0, memory_order_acq_rel);
        (void)atomic_exchange_explicit(&g_shm->proc_ocr[slot].ru_hw_rfo_pf, 0, memory_order_acq_rel);
    }
}

/* ── iMC uncore setup/read (UNC_M_CAS_COUNT.WR / .RD = system-wide writes/reads) ── */

static int detect_imc_type_base(void)
{
    FILE *fp = fopen("/sys/devices/uncore_imc_0/type", "r");
    if (!fp) {
        TM_ERR("Cannot detect uncore_imc type");
        return -1;
    }
    int type;
    if (fscanf(fp, "%d", &type) != 1) { fclose(fp); return -1; }
    fclose(fp);
    return type;
}

/* Read cpumask "0,28" to determine which CPU to use per node. */
static void detect_imc_cpus(void)
{
    imc_cpu_for_node[0] = 0;
    imc_cpu_for_node[1] = NUM_CPUS_PER_NODE;

    FILE *fp = fopen("/sys/devices/uncore_imc_0/cpumask", "r");
    if (!fp) return;

    char buf[256];
    if (!fgets(buf, sizeof(buf), fp)) { fclose(fp); return; }
    fclose(fp);

    int idx = 0;
    char *tok = strtok(buf, ",\n");
    while (tok && idx < NUM_NODES) {
        imc_cpu_for_node[idx++] = atoi(tok);
        tok = strtok(NULL, ",\n");
    }
}

static int setup_imc_events(void)
{
    imc_type_base = detect_imc_type_base();
    if (imc_type_base < 0)
        return -1;

    detect_imc_cpus();
    TM_DBG("iMC type base=%d, cpu_for_node=[%d,%d]",
           imc_type_base, imc_cpu_for_node[0], imc_cpu_for_node[1]);

    for (int node = 0; node < NUM_NODES; node++)
        for (int ch = 0; ch < NUM_IMC_CHANNELS; ch++) {
            g_monitor.imc_wr_fds[node][ch] = -1;
            g_monitor.imc_rd_fds[node][ch] = -1;
        }

    for (int ch = 0; ch < NUM_IMC_CHANNELS; ch++) {
        int imc_type = imc_type_base + ch;
        for (int node = 0; node < NUM_NODES; node++) {
            int cpu = imc_cpu_for_node[node];

            /* UNC_M_CAS_COUNT.WR: config=0xF005 (SPR) */
            struct perf_event_attr attr_wr;
            memset(&attr_wr, 0, sizeof(attr_wr));
            attr_wr.type     = imc_type;
            attr_wr.size     = sizeof(attr_wr);
            attr_wr.config   = 0xF005;
            attr_wr.disabled = 1;

            int fd = sys_perf_event_open(&attr_wr, -1, cpu, -1, 0);
            if (fd < 0) {
                TM_ERR("Failed to open iMC WR on node%d ch%d (type=%d cpu=%d): %s",
                       node, ch, imc_type, cpu, strerror(errno));
                cleanup_imc_events();
                return -1;
            }
            g_monitor.imc_wr_fds[node][ch] = fd;

            /* UNC_M_CAS_COUNT.RD: config=0xCF05 (SPR) — diagnosis only */
            struct perf_event_attr attr_rd;
            memset(&attr_rd, 0, sizeof(attr_rd));
            attr_rd.type     = imc_type;
            attr_rd.size     = sizeof(attr_rd);
            attr_rd.config   = 0xCF05;
            attr_rd.disabled = 1;

            int fd_rd = sys_perf_event_open(&attr_rd, -1, cpu, -1, 0);
            if (fd_rd < 0) {
                TM_ERR("Failed to open iMC RD on node%d ch%d (type=%d cpu=%d): %s",
                       node, ch, imc_type, cpu, strerror(errno));
                cleanup_imc_events();
                return -1;
            }
            g_monitor.imc_rd_fds[node][ch] = fd_rd;
        }
    }

    TM_DBG("iMC WR/RD events opened: %d channels × %d nodes",
           NUM_IMC_CHANNELS, NUM_NODES);
    return 0;
}

static void read_imc_counters(void)
{
    memset(g_monitor.imc_wr_bytes, 0, sizeof(g_monitor.imc_wr_bytes));
    memset(g_monitor.imc_rd_bytes, 0, sizeof(g_monitor.imc_rd_bytes));

    for (int node = 0; node < NUM_NODES; node++) {
        for (int ch = 0; ch < NUM_IMC_CHANNELS; ch++) {
            if (g_monitor.imc_wr_fds[node][ch] >= 0) {
                uint64_t wr = perf_read_count(g_monitor.imc_wr_fds[node][ch]);
                uint64_t d_wr = wr - g_monitor.prev_imc_wr[node][ch];
                /* Each CAS_COUNT increment = 64 bytes */
                g_monitor.imc_wr_bytes[node] += d_wr * 64;
                g_monitor.prev_imc_wr[node][ch] = wr;
            }
            if (g_monitor.imc_rd_fds[node][ch] >= 0) {
                uint64_t rd = perf_read_count(g_monitor.imc_rd_fds[node][ch]);
                uint64_t d_rd = rd - g_monitor.prev_imc_rd[node][ch];
                g_monitor.imc_rd_bytes[node] += d_rd * 64;
                g_monitor.prev_imc_rd[node][ch] = rd;
            }
        }
    }
}

/* ── Per-object bandwidth computation ── */

static inline int proc_slot_for(pid_t pid)
{
    for (int i = 0; i < g_monitor.ocr_proc_count; i++)
        if (g_monitor.ocr_procs[i].pid == pid) return i;
    return -1;
}

#ifdef TIERMEM_DEBUG_REGULARITY
/*
 * Dump per-object stride histograms to a CSV file, one row per (object, kind)
 * per epoch. Enabled at build time via -DTIERMEM_DEBUG_REGULARITY.
 * Path is fixed to /tmp/spectra-stride-bins.csv for debug builds.
 */
#define TIERMEM_DEBUG_REGULARITY_CSV \
    "/tmp/spectra-stride-bins.csv"

static void debug_dump_stride_bins(const mem_object_t *o)
{
    static FILE *f = NULL;
    if (!f) {
        f = fopen(TIERMEM_DEBUG_REGULARITY_CSV, "w");
        if (!f) return;
        fprintf(f, "epoch,pid,start_addr,size,kind,samples,regularity");
        for (int b = 0; b < REG_NBINS; b++)
            fprintf(f, ",bin_%d", b);
        fprintf(f, "\n");
    }

    const struct {
        const char     *kind;
        const uint32_t *bins;
        uint64_t        samples;
    } rows[2] = {
        { "load",  o->load_stride_bins,
                   o->allload_sample_count >= o->pf_sample_count
                   ? o->allload_sample_count - o->pf_sample_count
                   : 0 },
        { "store", o->store_stride_bins, o->store_sample_count },
    };

    for (int r = 0; r < 2; r++) {
        fprintf(f, "%lu,%d,0x%lx,%zu,%s,%lu,%.6f",
                (unsigned long)g_monitor.epoch_counter,
                (int)o->pid,
                (unsigned long)o->start_addr,
                o->size,
                rows[r].kind,
                (unsigned long)rows[r].samples,
                regularity(rows[r].bins));
        for (int b = 0; b < REG_NBINS; b++)
            fprintf(f, ",%u", rows[r].bins[b]);
        fprintf(f, "\n");
    }
    fflush(f);
}
#endif /* TIERMEM_DEBUG_REGULARITY */

/* Per-object epoch-end derived terms used only inside
 * compute_per_object_bw_new — kept off mem_object_t so the struct stays lean. */
struct obj_derived {
    double demand_data_rd;
    double hw_data_pf;          /* HW-prefetch share of total_data_pf (per object) */
    double sw_data_pf;          /* SW-prefetch share of total_data_pf (per object) */
    double demand_rfo;
    double hw_rfo_pf;
    double store_hit_load;
    double avg_store_lat;
    double reg_load_raw;
    double reg_load;
    double reg_store_raw;
    double reg_store;
    double w_hwpf;              /* per-object weight for the HW-prefetch pool split */
};

static void compute_per_object_bw_new(mem_object_t **arr, int n, double T)
{
    struct obj_derived *d = real_calloc((size_t)n, sizeof(*d));
    if (!d) return;

    /* Saturation threshold for per-object regularity: values below theta are
     * snapped to 0 (treated as fully irregular), values above 1-theta are
     * snapped to 1 (treated as fully regular). When every object in a process
     * saturates to 0, the regularity-weighted denominator collapses and we
     * fall back to dividing the per-process prefetch totals equally. */
    const double theta = g_config.reg_theta;

    /* Per-proc accumulators. Sized to MAX_PROCS — we index by ocr_procs slot. */
    double S_load_samples[MAX_PROCS]= {0};
    double S_allload[MAX_PROCS]     = {0};
    double S_pf_samples[MAX_PROCS]  = {0};
    double S_hwpf_w[MAX_PROCS]      = {0};
    double S_store_lat_sum[MAX_PROCS] = {0};
    double S_rfo_reg[MAX_PROCS]     = {0};
    double S_demand_rfo[MAX_PROCS]  = {0};
    double S_hw_rfo_pf[MAX_PROCS]   = {0};
    int    N_proc[MAX_PROCS]        = {0};

    /* Pass 0 — per-proc PEBS load-sample totals (attribution denominator) */
    for (int i = 0; i < n; i++) {
        mem_object_t *o = arr[i];
        int p = proc_slot_for(o->pid);
        if (p < 0) continue;
        S_load_samples[p] += (double)o->load_sample_count;
        S_allload[p]      += (double)o->allload_sample_count;
        S_pf_samples[p]   += (double)o->pf_sample_count;
    }

    /* Process-wide ratio: SW-prefetch share of all_loads samples.
     * The OCR.TOTAL_DATA_PF.L3_MISS magnitude (carried in epoch_hw_data_pf
     * after the mask was widened in Task 1) is split into:
     *   total_data_swpf[p] = total_pf * (pf_samples * 2 / allload_samples)
     *   total_data_hwpf[p] = total_pf - swpf
     * Falls back to all-HW if allload_samples is 0 (no PEBS coverage).
     * pf_samples * 2 since a swpf is usually followed by a normal load */
    double total_data_hwpf[MAX_PROCS];
    double total_data_swpf[MAX_PROCS];
    for (int p = 0; p < MAX_PROCS; p++) {
        double total = (double)g_monitor.ocr_procs[p].epoch_hw_data_pf;
        double ratio = (S_allload[p] > 0.0)
                       ? S_pf_samples[p] * 2 / S_allload[p]
                       : 0.0;
        ratio = ratio > 1.0 ? 1.0 : ratio;
        total_data_swpf[p] = total * ratio;
        total_data_hwpf[p] = total - total_data_swpf[p];
    }

    /* Pass 1 — primitives + regularity + per-proc bases.
     *
     * demand_data_rd is OCR-anchored: the process-wide total comes from
     * OCR.DEMAND_DATA_RD.L3_MISS (a counting event, correct magnitude even
     * under PEBS multiplexing and free of the semantic inflation of
     * MEM_LOAD_RETIRED.L3_MISS).  PEBS load samples are used only as
     * per-object attribution weights within that total. */
    for (int i = 0; i < n; i++) {
        mem_object_t *o = arr[i];

        int p = proc_slot_for(o->pid);
        if (p >= 0 && S_load_samples[p] > 0.0) {
            double ocr_total = (double)g_monitor.ocr_procs[p].epoch_demand_data_rd;
            d[i].demand_data_rd = ocr_total * (double)o->load_sample_count /
                                  S_load_samples[p];
        }
        d[i].avg_store_lat = o->store_sample_count
                           ? (double)o->store_lat_sum / (double)o->store_sample_count
                           : 0.0;
        double rl = regularity(o->load_stride_bins);
        double rs = regularity(o->store_stride_bins);
        d[i].reg_load_raw = rl;
        d[i].reg_store_raw = rs;
        d[i].reg_load  = regularity_theta_gate(rl, theta);
        d[i].reg_store = regularity_theta_gate(rs, theta);

#ifdef TIERMEM_DEBUG_REGULARITY
        debug_dump_stride_bins(o);
#endif

        if (p < 0) continue;
        N_proc[p]   += 1;

        /* HW-prefetch attribution weight.  demand_data_rd alone under-weights
         * SW-prefetched streams: their prefetch beats the demand load to the
         * line, so the load hits cache and is not an L3 miss, collapsing their
         * demand-miss share even though they stream at full bandwidth.  Add an
         * estimate of retired SW-prefetch lines (pf_sample_count * allload
         * period; period-independent in expectation) so such objects can claim
         * their share of the HW-prefetch pool.  pow(reg_load, gamma) gates the
         * whole weight on stream regularity so irregular (random) objects, which
         * trigger little HW prefetch, are sharply suppressed. */
        double pf_lines = (double)o->pf_sample_count
                        * (double)g_config.allload_period;
        d[i].w_hwpf = pow(d[i].reg_load, g_config.pf_reg_gamma)
                    * (d[i].demand_data_rd + g_config.pf_sw_kappa * pf_lines);
        S_hwpf_w[p] += d[i].w_hwpf;
        S_store_lat_sum[p] += (double)o->store_lat_sum;
    }

    /* Pass 3 (hw_data_pf, demand_rfo) + Pass-3-post sums */
    for (int i = 0; i < n; i++) {
        mem_object_t *o = arr[i];
        int p = proc_slot_for(o->pid);
        if (p < 0) continue;
        proc_ocr_t *po = &g_monitor.ocr_procs[p];

        d[i].hw_data_pf = (S_hwpf_w[p] > 0.0)
            ? total_data_hwpf[p] * d[i].w_hwpf / S_hwpf_w[p]
            : (N_proc[p] > 0
               ? total_data_hwpf[p] / (double)N_proc[p]
               : 0.0);

        /* SW-prefetch: distribute the SW share of total_data_pf across
         * objects of the same process proportional to per-object pf_sample
         * count (each retired PREFETCH* uop traces back to the object). */
        d[i].sw_data_pf = (S_pf_samples[p] > 0.0)
            ? total_data_swpf[p]
              * (double)o->pf_sample_count / S_pf_samples[p]
            : 0.0;

        d[i].demand_rfo = (S_store_lat_sum[p] > 0.0)
            ? (double)po->epoch_demand_rfo
              * (double)o->store_lat_sum / S_store_lat_sum[p]
            : 0.0;

        S_rfo_reg[p]    += d[i].demand_rfo * d[i].reg_store;
        S_demand_rfo[p] += d[i].demand_rfo;
    }

    /* Pass 4 — hw_rfo_pf + accumulate S_hw_rfo_pf */
    for (int i = 0; i < n; i++) {
        mem_object_t *o = arr[i];
        int p = proc_slot_for(o->pid);
        if (p < 0) continue;
        proc_ocr_t *po = &g_monitor.ocr_procs[p];

        d[i].hw_rfo_pf = (S_rfo_reg[p] > 0.0)
            ? (double)po->epoch_hw_rfo_pf
              * (d[i].demand_rfo * d[i].reg_store) / S_rfo_reg[p]
            : (N_proc[p] > 0
               ? (double)po->epoch_hw_rfo_pf / (double)N_proc[p]
               : 0.0);
        S_hw_rfo_pf[p] += d[i].hw_rfo_pf;
    }

    /* Pass 5 — system-wide residual store_hit_load.
     *
     * Ground truth: UNC_M_CAS_COUNT.WR (iMC WR CAS) — total writes that reach
     * DRAM across all channels on all sockets, in cacheline units.  The
     * residual after subtracting system-wide demand_rfo + hw_rfo_pf is
     * attributed to store-hit loads (RFO-fetched lines that absorb later
     * stores).  Distribute that residual across all objects proportionally
     * to (demand_data_rd + hw_data_pf) * store_sample_count: store-hit
     * fetches ride on top of read traffic, but only on objects that are
     * actually being stored to. */
    uint64_t imc_wr_cas = 0;
    for (int node = 0; node < NUM_NODES; node++)
        imc_wr_cas += g_monitor.imc_wr_bytes[node] / 64;

    double T_demand_rfo = 0.0, T_hw_rfo_pf = 0.0;
    for (int p = 0; p < g_monitor.ocr_proc_count; p++) {
        T_demand_rfo += S_demand_rfo[p];
        T_hw_rfo_pf  += S_hw_rfo_pf[p];
    }
    double R = (double)imc_wr_cas - T_demand_rfo - T_hw_rfo_pf;
    if (R < 0.0) R = 0.0;

    double T_shl_weight = 0.0;
    for (int i = 0; i < n; i++) {
        T_shl_weight += (d[i].demand_data_rd + d[i].hw_data_pf)
                      * (double)arr[i]->store_sample_count;
    }

    for (int i = 0; i < n; i++) {
        double w = (d[i].demand_data_rd + d[i].hw_data_pf)
                 * (double)arr[i]->store_sample_count;
        d[i].store_hit_load = (T_shl_weight > 0.0)
            ? R * w / T_shl_weight
            : 0.0;
    }

    /* Pass 6 — final BW + EMA smoothing.
     *
     * The L3-miss-based magnitude anchors (OCR.DEMAND_DATA_RD.L3_MISS,
     * OCR.HW_DATA_PF.L3_MISS) are placement-biased: the same object reads
     * substantially higher BW on the remote tier (CXL) than on local DRAM
     * because local-tier caches absorb more demand+prefetch traffic. Without
     * smoothing this drives every-epoch ping-pong on objects whose true BW
     * sits near the budget boundary. EMA blends the new sample with prior
     * state so a single placement-induced swing cannot flip the ranking. */
    double alpha = g_config.bw_ema_alpha;
    for (int i = 0; i < n; i++) {
        mem_object_t *o = arr[i];
        o->rd_bw = (d[i].demand_data_rd + d[i].hw_data_pf + d[i].sw_data_pf
                  + d[i].demand_rfo + d[i].hw_rfo_pf) * 64.0 / T;
        o->wr_bw = (d[i].demand_rfo + d[i].hw_rfo_pf + d[i].store_hit_load) * 64.0 / T;
        o->bw    = o->rd_bw + o->wr_bw;

        if (alpha <= 0.0 || o->bw_ema == 0.0)
            o->bw_ema = o->bw;
        else
            o->bw_ema = alpha * o->bw + (1.0 - alpha) * o->bw_ema;
    }

    /* Per-object epoch log — emitted here because the derived terms are local
     * to this function and not retained on mem_object_t. Mirrors the format
     * used elsewhere for per-epoch object summaries. */
    for (int i = 0; i < n; i++) {
        mem_object_t *o = arr[i];
        TM_EPOCH("  obj %#lx (%zu pages, node %d, pid %d): "
                 "loads=%lu stores=%lu allloads=%lu pf=%lu "
                 "lat=%.1f reg_ld_raw=%.2f reg_ld=%.2f reg_st_raw=%.2f reg_st=%.2f "
                 "dd_rd=%.2e hw_dp=%.2e sw_dp=%.2e d_rfo=%.2e hw_rp=%.2e shl=%.2e "
                 "rd_bw=%.2f GB/s wr_bw=%.2f GB/s bw=%.2f GB/s bw_ema=%.2f GB/s",
                 o->start_addr, o->nr_pages, o->current_node,
                 (int)o->pid,
                 o->load_sample_count, o->store_sample_count,
                 o->allload_sample_count, o->pf_sample_count,
                 d[i].avg_store_lat, d[i].reg_load_raw, d[i].reg_load,
                 d[i].reg_store_raw, d[i].reg_store,
                 d[i].demand_data_rd, d[i].hw_data_pf, d[i].sw_data_pf,
                 d[i].demand_rfo, d[i].hw_rfo_pf, d[i].store_hit_load,
                 o->rd_bw / 1e9, o->wr_bw / 1e9, o->bw / 1e9, o->bw_ema / 1e9);
    }

    real_free(d);
}

/* ── Ranking and migration decisions ── */

struct obj_collect_ctx {
    mem_object_t **array;
    int count;
    int capacity;
};

static void collect_obj(mem_object_t *obj, void *ctx)
{
    struct obj_collect_ctx *c = (struct obj_collect_ctx *)ctx;
    if (c->count < c->capacity)
        c->array[c->count++] = obj;
}

/* Size-aware ranking: sort by value per 4 KiB page and pack greedily until
 * the DRAM budget is exhausted, skipping objects that do not fit. */
static int cmp_bw_desc(const void *a, const void *b)
{
    const mem_object_t *obj_a = *(mem_object_t * const *)a;
    const mem_object_t *obj_b = *(mem_object_t * const *)b;

    if (obj_a->nr_pages == 0 && obj_b->nr_pages != 0) return  1;
    if (obj_a->nr_pages != 0 && obj_b->nr_pages == 0) return -1;
    if (obj_a->nr_pages != 0 && obj_b->nr_pages != 0) {
        long double lhs = (long double)obj_a->bw_ema * (long double)obj_b->nr_pages;
        long double rhs = (long double)obj_b->bw_ema * (long double)obj_a->nr_pages;
        if (lhs > rhs) return -1;
        if (lhs < rhs) return  1;
    }

    if (obj_a->bw_ema > obj_b->bw_ema) return -1;
    if (obj_a->bw_ema < obj_b->bw_ema) return  1;
    return 0;
}

static double obj_bw_ema_per_page(const mem_object_t *obj)
{
    if (obj->nr_pages == 0)
        return 0.0;
    return obj->bw_ema / (double)obj->nr_pages;
}

/* Query node for objects that haven't been queried yet (pages not faulted at insert time) */
static void resolve_obj_node(mem_object_t *obj, void *ctx)
{
    (void)ctx;
    if (obj->current_node >= 0) return; /* already known */

    /* Query the first faulted page. Try a few offsets. */
    for (size_t off = 0; off < obj->nr_pages && off < 16; off++) {
        void *page = (void *)(obj->start_addr + off * TM_PAGE_SIZE);
        int status = -1;
        long ret = syscall(__NR_move_pages, 0, 1, &page, NULL, &status, 0);
        if (ret == 0 && status >= 0) {
            obj->current_node = status;
            TM_DBG("Resolved obj %#lx node=%d", obj->start_addr, status);
            return;
        }
    }
    /* Still unknown — default to CXL */
    obj->current_node = CXL_NODE;
}

static void rank_and_decide(void)
{
    if (g_config.dram_budget_bytes == 0) return; /* No budget = no migration */

    /* Resolve any unknown node assignments */
    obj_store_foreach(resolve_obj_node, NULL);

    /* Collect all objects */
    int max_objs = 1024;
    mem_object_t **sorted = real_malloc(max_objs * sizeof(mem_object_t *));
    if (!sorted) return;

    struct obj_collect_ctx ctx = { .array = sorted, .count = 0, .capacity = max_objs };
    obj_store_foreach(collect_obj, &ctx);

    if (ctx.count == 0) {
        real_free(sorted);
        return;
    }

    /* Sort by EMA BW per page descending */
    qsort(sorted, ctx.count, sizeof(mem_object_t *), cmp_bw_desc);

    /* Greedy knapsack: fill DRAM budget */
    size_t dram_budget_pages = g_config.dram_budget_bytes / TM_PAGE_SIZE;
    size_t filled = 0;

    /* Compute hysteresis threshold:
     * Find the EMA BW/page at the budget boundary to determine the hysteresis
     * band. Ranking and gating use bw_ema/nr_pages, not total bw_ema or the
     * raw per-epoch bw, so a single noisy or placement-biased sample cannot
     * flip placement on its own. */
    double threshold_bw_per_page = 0.0;
    {
        size_t accum = 0;
        for (int i = 0; i < ctx.count; i++) {
            accum += sorted[i]->nr_pages;
            if (accum > dram_budget_pages) {
                threshold_bw_per_page = obj_bw_ema_per_page(sorted[i]);
                break;
            }
        }
    }
    double hysteresis_band_per_page =
        threshold_bw_per_page * g_config.hysteresis_pct / 100.0;
    TM_DBG("DRAM budget: %zu pages, threshold_bw=%.2f MB/s/page, hysteresis_band=%.2f MB/s/page",
           dram_budget_pages, threshold_bw_per_page / 1e6,
           hysteresis_band_per_page / 1e6);

    for (int i = 0; i < ctx.count; i++) {
        mem_object_t *obj = sorted[i];
        double obj_bw_per_page = obj_bw_ema_per_page(obj);

        if (filled + obj->nr_pages <= dram_budget_pages) {
            /* Should be in local DRAM */
            if (obj->current_node != LOCAL_NODE) {
                /* Apply hysteresis: only promote if EMA BW/page above threshold + delta */
                if (obj_bw_per_page > threshold_bw_per_page + hysteresis_band_per_page ||
                    threshold_bw_per_page == 0.0) {
                    obj->migration_pending = true;
                    obj->target_node = LOCAL_NODE;
                }
            }
            filled += obj->nr_pages;
        } else {
            /* Should be on CXL */
            if (obj->current_node != CXL_NODE) {
                /* Apply hysteresis: only demote if EMA BW/page below threshold - delta */
                if (obj_bw_per_page < threshold_bw_per_page - hysteresis_band_per_page) {
                    obj->migration_pending = true;
                    obj->target_node = CXL_NODE;
                }
            }
        }
    }

    real_free(sorted);
}

/* ── Monitor thread main loop ── */

static void *monitor_thread_func(void *arg)
{
    (void)arg;

    /* Pin to monitor CPU */
    cpu_set_t cpuset;
    CPU_ZERO(&cpuset);
    CPU_SET(g_config.monitor_cpu, &cpuset);
    sched_setaffinity(0, sizeof(cpuset), &cpuset);

    /* Set realtime priority */
    struct sched_param param = { .sched_priority = 99 };
    sched_setscheduler(0, SCHED_FIFO, &param);

    g_monitor.monitor_tid_kernel = (pid_t)syscall(SYS_gettid);
    TM_DBG("Monitor thread started (tid=%d, cpu=%d)",
           g_monitor.monitor_tid_kernel, g_config.monitor_cpu);

    struct timespec mon_wall_start, mon_cpu_start;
    clock_gettime(CLOCK_MONOTONIC, &mon_wall_start);
    clock_gettime(CLOCK_THREAD_CPUTIME_ID, &mon_cpu_start);

    /* Warmup phase: let application initialize before profiling */
    if (g_config.warmup_sec > 0.0 && g_monitor.running) {
        TM_INFO("[%s] Warmup: sleeping %.1f sec before enabling monitoring",
                tm_log_wall_time(), g_config.warmup_sec);
        struct timespec warmup_ts;
        warmup_ts.tv_sec  = (time_t)g_config.warmup_sec;
        warmup_ts.tv_nsec = (long)((g_config.warmup_sec -
                             (double)warmup_ts.tv_sec) * 1e9);
        nanosleep(&warmup_ts, NULL);
        TM_INFO("Warmup completed, enabling monitoring");
    }

    if (!g_monitor.running) goto out;

    /* Enable perf events after warmup */
    monitor_enable_events();

    struct timespec sleep_ts;
    sleep_ts.tv_sec  = g_config.ocr_interval_ms / 1000;
    sleep_ts.tv_nsec = (g_config.ocr_interval_ms % 1000) * 1000000L;

    while (g_monitor.running) {
        clock_gettime(CLOCK_MONOTONIC, &g_monitor.epoch_start);
        uint64_t epoch_load_samples_start = g_monitor.samples_collected;
        uint64_t epoch_store_samples_start = g_monitor.store_samples_collected;

        /* Reset per-process OCR epoch accumulators (single-proc entries only;
         * multi-proc entries are zeroed by collect_shm_ocr's atomic_exchange) */
        for (int i = 0; i < g_monitor.ocr_proc_count; i++) {
            if (g_monitor.ocr_procs[i].fd_demand_data_rd >= 0) {
                g_monitor.ocr_procs[i].epoch_demand_data_rd = 0;
                g_monitor.ocr_procs[i].epoch_demand_rfo     = 0;
                g_monitor.ocr_procs[i].epoch_hw_data_pf     = 0;
                g_monitor.ocr_procs[i].epoch_hw_rfo_pf      = 0;
            }
        }

        /* Multi-process: register proc_ocr_t entries for newly joined processes */
        check_new_procs_ocr();

        /* ── Phase A: Collect throughout epoch ── */
        struct timespec epoch_end;
        epoch_end.tv_sec  = g_monitor.epoch_start.tv_sec + (int)g_config.epoch_sec;
        epoch_end.tv_nsec = g_monitor.epoch_start.tv_nsec +
            (long)((g_config.epoch_sec - (int)g_config.epoch_sec) * 1e9);
        if (epoch_end.tv_nsec >= 1000000000L) {
            epoch_end.tv_sec++;
            epoch_end.tv_nsec -= 1000000000L;
        }

        while (g_monitor.running) {
            nanosleep(&sleep_ts, NULL);

            struct timespec now;
            clock_gettime(CLOCK_MONOTONIC, &now);
            if (now.tv_sec > epoch_end.tv_sec ||
                (now.tv_sec == epoch_end.tv_sec && now.tv_nsec >= epoch_end.tv_nsec))
                break;

            /* Read OCR counters (single-proc: read fds; multi-proc: leader's own to shm) */
            read_ocr_counters();
            if (g_config.multi_proc)
                ocr_self_read_to_shm();

            /* Drain PEBS ring buffers */
            for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
                drain_pebs_buffer(cpu);
                drain_pebs_store_buffer(cpu);
                drain_pebs_allload_buffer(cpu);
            }
        }

        if (!g_monitor.running) break;

        /* Final drain + read at epoch boundary */
        read_ocr_counters();
        if (g_config.multi_proc)
            ocr_self_read_to_shm();
        /* Harvest all processes' OCR from shared memory */
        collect_shm_ocr();
        /* System-wide iMC WR counters (ground truth for total writes) */
        read_imc_counters();
        for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
            drain_pebs_buffer(cpu);
            drain_pebs_store_buffer(cpu);
            drain_pebs_allload_buffer(cpu);
        }
        if (g_monitor.samples_collected == epoch_load_samples_start &&
            g_monitor.store_samples_collected == epoch_store_samples_start) {
            goto reset_counters;
        }

        /* ── Phase B: End-of-epoch computation ── */
        struct timespec now;
        clock_gettime(CLOCK_MONOTONIC, &now);
        double T = (now.tv_sec - g_monitor.epoch_start.tv_sec) +
                   (now.tv_nsec - g_monitor.epoch_start.tv_nsec) / 1e9;
        if (T <= 0.0) T = g_config.epoch_sec;

        /* Step 1: Compute per-object BW via six-pass attribution */
        {
            int max_objs = 4096;
            mem_object_t **sorted = real_malloc(max_objs * sizeof(mem_object_t *));
            struct obj_collect_ctx cctx = { sorted, 0, max_objs };
            if (sorted) obj_store_foreach(collect_obj, &cctx);

            if (sorted && cctx.count > 0) {
                compute_per_object_bw_new(sorted, cctx.count, T);
            }
            if (sorted) real_free(sorted);
        }

        /* Step 4/5: the congestion controller (when active) owns placement and
         * each process interleaves its own local objects; otherwise the base
         * bandwidth knapsack ranks and each process migrates its own pending. */
        double cc_r = 0.0, cc_dmax = 0.0;
        int    cc_g = 0;
        bool cc_owns = congest_ctrl_decide(T, &cc_r, &cc_dmax, &cc_g);

        /* Step 4: Rank and decide (skipped while the controller owns placement) */
        if (!cc_owns) rank_and_decide();

        /* Step 5: Execute migrations */
        if (g_config.multi_proc && g_shm) {
            /* Multi-process: publish the controller decision, then signal all
             * processes to migrate their own objects. */
            epoch_sync_t *es = shm_epoch_sync();
            atomic_store_explicit(&es->cc_owns, cc_owns ? 1 : 0, memory_order_release);
            atomic_store_explicit(&es->cc_r, cc_r, memory_order_release);
            atomic_store_explicit(&es->cc_density_max, cc_dmax, memory_order_release);
            atomic_store_explicit(&es->cc_g, cc_g, memory_order_release);

            atomic_store_explicit(&es->migrate_done, 0, memory_order_release);
            atomic_store_explicit(&es->phase, PHASE_MIGRATING,
                                 memory_order_release);
            atomic_fetch_add_explicit(&es->futex_word, 1, memory_order_release);
            shm_futex_wake(&es->futex_word, INT_MAX);

            /* Leader migrates its own objects (controller interleave or base). */
            if (cc_owns) congest_ctrl_migrate_local(cc_r, cc_dmax, cc_g, false);
            else         migrate_execute_own_pending();

            /* Leader counts towards barrier */
            atomic_fetch_add_explicit(&es->migrate_done, 1,
                                     memory_order_release);
            atomic_fetch_add_explicit(&es->futex_word, 1,
                                     memory_order_release);
            shm_futex_wake(&es->futex_word, INT_MAX);

            /* Wait for all processes to finish migrating */
            int target = atomic_load_explicit(&es->barrier_target,
                                              memory_order_acquire);
            while (atomic_load_explicit(&es->migrate_done,
                                        memory_order_acquire) < target) {
                int fw = atomic_load_explicit(&es->futex_word,
                                              memory_order_acquire);
                struct timespec wait_ts = { .tv_sec = 0, .tv_nsec = 10000000 };
                /* Poll with short timeout instead of blocking */
                nanosleep(&wait_ts, NULL);
                (void)fw;
            }

            /* Signal epoch done */
            atomic_store_explicit(&es->phase, PHASE_DONE, memory_order_release);
            atomic_fetch_add_explicit(&es->futex_word, 1, memory_order_release);
            shm_futex_wake(&es->futex_word, INT_MAX);

            /* Check for dead processes */
            shm_check_dead_procs();
        } else {
            /* Single-process: direct migration */
            if (cc_owns) congest_ctrl_migrate_local(cc_r, cc_dmax, cc_g, true);
            else         migrate_execute_pending();
        }

        /* Epoch logging */
        TM_EPOCH("[%s] === Epoch %lu (T=%.2fs) ===",
                 tm_log_wall_time(), g_monitor.epoch_counter, T);
        for (int i = 0; i < g_monitor.ocr_proc_count; i++) {
            proc_ocr_t *po = &g_monitor.ocr_procs[i];
            if (po->epoch_demand_data_rd || po->epoch_demand_rfo ||
                po->epoch_hw_data_pf || po->epoch_hw_rfo_pf) {
                TM_EPOCH("  pid %d: dd_rd=%lu d_rfo=%lu hw_dp=%lu hw_rp=%lu",
                         (int)po->pid,
                         po->epoch_demand_data_rd, po->epoch_demand_rfo,
                         po->epoch_hw_data_pf, po->epoch_hw_rfo_pf);
            }
        }
        TM_EPOCH("  iMC WR: node0=%.2f GB/s node1=%.2f GB/s",
                 g_monitor.imc_wr_bytes[0] / T / 1e9,
                 g_monitor.imc_wr_bytes[1] / T / 1e9);
        TM_EPOCH("  iMC RD: node0=%.2f GB/s node1=%.2f GB/s",
                 g_monitor.imc_rd_bytes[0] / T / 1e9,
                 g_monitor.imc_rd_bytes[1] / T / 1e9);
        TM_EPOCH("  PEBS load:  collected=%lu unmatched=%lu lost=%lu",
                 g_monitor.samples_collected, g_monitor.samples_unmatched,
                 g_monitor.samples_lost);
        TM_EPOCH("  PEBS store: collected=%lu unmatched=%lu lost=%lu",
                 g_monitor.store_samples_collected,
                 g_monitor.store_samples_unmatched,
                 g_monitor.store_samples_lost);
        TM_EPOCH("  PEBS allload: collected=%lu pf=%lu unmatched=%lu lost=%lu",
                 g_monitor.allload_samples_collected,
                 g_monitor.allload_samples_pf,
                 g_monitor.allload_samples_unmatched,
                 g_monitor.allload_samples_lost);
        {
            struct swpf_cache_stats st;
            swpf_cache_get_stats(&st);
            TM_EPOCH("  SWPF cache: hits=%lu misses=%lu read_fail=%lu pf=%lu non_pf=%lu",
                     st.hits, st.misses, st.read_failures,
                     st.pf_verdicts, st.non_pf_verdicts);
        }

        /* Diagnostic: per-CPU PEBS hardware-counter deltas + multiplex ratio.
         * raw_sum    = Σ Δvalue (as read; counter only runs when active)
         * scaled_sum = Σ Δvalue × (Δtime_enabled / Δtime_running)
         * ru/en      = time_running / time_enabled fraction (1.0 = no multiplex) */
        {
            static uint64_t prev_val_l[NUM_CPUS_PER_NODE];
            static uint64_t prev_en_l [NUM_CPUS_PER_NODE];
            static uint64_t prev_ru_l [NUM_CPUS_PER_NODE];
            static uint64_t prev_val_s[NUM_CPUS_PER_NODE];
            static uint64_t prev_en_s [NUM_CPUS_PER_NODE];
            static uint64_t prev_ru_s [NUM_CPUS_PER_NODE];
            uint64_t raw_l = 0, scaled_l = 0, en_l_sum = 0, ru_l_sum = 0;
            uint64_t raw_s = 0, scaled_s = 0, en_s_sum = 0, ru_s_sum = 0;
            double min_l = 2.0, max_l = 0.0, min_s = 2.0, max_s = 0.0;
            int n_l = 0, n_s = 0;

            for (int cpu = 0; cpu < NUM_CPUS_PER_NODE; cpu++) {
                if (g_monitor.pebs_fd[cpu] >= 0) {
                    struct perf_read_scaled r = perf_read_count_scaled(g_monitor.pebs_fd[cpu]);
                    uint64_t dv = r.value - prev_val_l[cpu];
                    uint64_t de = r.time_enabled - prev_en_l[cpu];
                    uint64_t dr = r.time_running - prev_ru_l[cpu];
                    prev_val_l[cpu] = r.value;
                    prev_en_l[cpu]  = r.time_enabled;
                    prev_ru_l[cpu]  = r.time_running;
                    if (de > 0 && dv > 0) {
                        uint64_t sc = (dr > 0) ? (uint64_t)((double)dv * (double)de / (double)dr) : dv;
                        double ratio = (double)dr / (double)de;
                        raw_l    += dv;
                        scaled_l += sc;
                        en_l_sum += de;
                        ru_l_sum += dr;
                        if (ratio < min_l) min_l = ratio;
                        if (ratio > max_l) max_l = ratio;
                        n_l++;
                    }
                }
                if (g_monitor.pebs_store_fd[cpu] >= 0) {
                    struct perf_read_scaled r = perf_read_count_scaled(g_monitor.pebs_store_fd[cpu]);
                    uint64_t dv = r.value - prev_val_s[cpu];
                    uint64_t de = r.time_enabled - prev_en_s[cpu];
                    uint64_t dr = r.time_running - prev_ru_s[cpu];
                    prev_val_s[cpu] = r.value;
                    prev_en_s[cpu]  = r.time_enabled;
                    prev_ru_s[cpu]  = r.time_running;
                    if (de > 0 && dv > 0) {
                        uint64_t sc = (dr > 0) ? (uint64_t)((double)dv * (double)de / (double)dr) : dv;
                        double ratio = (double)dr / (double)de;
                        raw_s    += dv;
                        scaled_s += sc;
                        en_s_sum += de;
                        ru_s_sum += dr;
                        if (ratio < min_s) min_s = ratio;
                        if (ratio > max_s) max_s = ratio;
                        n_s++;
                    }
                }
            }
            double avg_l = en_l_sum ? (double)ru_l_sum / (double)en_l_sum : 0.0;
            double avg_s = en_s_sum ? (double)ru_s_sum / (double)en_s_sum : 0.0;
            if (n_l > 0)
                TM_EPOCH("  PEBS load  HW: raw=%.3e scaled=%.3e ru/en avg=%.3f min=%.3f max=%.3f (%d cpus active)",
                         (double)raw_l, (double)scaled_l, avg_l, min_l, max_l, n_l);
            if (n_s > 0)
                TM_EPOCH("  PEBS store HW: raw=%.3e scaled=%.3e ru/en avg=%.3f min=%.3f max=%.3f (%d cpus active)",
                         (double)raw_s, (double)scaled_s, avg_s, min_s, max_s, n_s);
        }

reset_counters:
        /* Step 6: Reset per-epoch counters */
        obj_store_epoch_reset();
        g_monitor.epoch_counter++;

        /* Multi-process: transition to SAMPLING for next epoch */
        if (g_config.multi_proc && g_shm) {
            epoch_sync_t *es = shm_epoch_sync();
            atomic_store_explicit(&es->phase, PHASE_SAMPLING,
                                 memory_order_release);
            atomic_fetch_add_explicit(&es->futex_word, 1, memory_order_release);
            shm_futex_wake(&es->futex_word, INT_MAX);
        }
        TM_EPOCH("\n");
    }

    TM_DBG("Monitor thread exiting");
out:
    {
        struct timespec mon_wall_end, mon_cpu_end;
        clock_gettime(CLOCK_MONOTONIC, &mon_wall_end);
        clock_gettime(CLOCK_THREAD_CPUTIME_ID, &mon_cpu_end);
        double elapsed = (mon_wall_end.tv_sec - mon_wall_start.tv_sec) +
                         (mon_wall_end.tv_nsec - mon_wall_start.tv_nsec) / 1e9;
        double cpu_t   = (mon_cpu_end.tv_sec  - mon_cpu_start.tv_sec) +
                         (mon_cpu_end.tv_nsec  - mon_cpu_start.tv_nsec) / 1e9;
        double usage   = (elapsed > 0.0) ? (cpu_t / elapsed * 100.0) : 0.0;
        TM_INFO("Monitor thread exit: elapsed=%.3fs cpu=%.3fs usage=%.2f%%",
                elapsed, cpu_t, usage);
    }
    return NULL;
}

/* ── Init / Cleanup ── */

int monitor_init(void)
{
    memset(&g_monitor, 0, sizeof(g_monitor));

    /* Initialize fd slots explicitly so cleanup can safely run after partial setup. */
    for (int i = 0; i < NUM_CPUS_PER_NODE; i++) {
        g_monitor.pebs_fd[i]       = -1;
        g_monitor.pebs_store_fd[i] = -1;
        g_monitor.pebs_allload_fd[i] = -1;
    }
    for (int i = 0; i < MAX_PROCS; i++) {
        g_monitor.ocr_procs[i].fd_demand_data_rd = -1;
        g_monitor.ocr_procs[i].fd_demand_rfo     = -1;
        g_monitor.ocr_procs[i].fd_hw_data_pf     = -1;
        g_monitor.ocr_procs[i].fd_hw_rfo_pf      = -1;
    }
    for (int node = 0; node < NUM_NODES; node++)
        for (int ch = 0; ch < NUM_IMC_CHANNELS; ch++) {
            g_monitor.imc_wr_fds[node][ch] = -1;
            g_monitor.imc_rd_fds[node][ch] = -1;
        }

    g_monitor.running = true;

    if (setup_pebs_store_events() != 0)
        return -1;
    if (setup_pebs_events() != 0) {
        cleanup_pebs_store_events();
        return -1;
    }
    if (setup_pebs_allload_events() != 0) {
        cleanup_pebs_events();
        cleanup_pebs_store_events();
        return -1;
    }
    if (setup_ocr_events() != 0) {
        cleanup_pebs_allload_events();
        cleanup_pebs_events();
        cleanup_pebs_store_events();
        return -1;
    }
    if (setup_imc_events() != 0) {
        TM_INFO("Warning: iMC WR/RD events unavailable, store_hit_load will be zero");
        /* Non-fatal: library still works, just without store_hit_load. */
    }

    /* Latency-based congestion controller (no-op unless TIERMEM_CONGEST_CTRL=1).
     * Non-fatal: failure just leaves the controller disabled. */
    congest_ctrl_init();

    TM_DBG("Monitor initialized");
    return 0;
}

int monitor_launch(void)
{
    pthread_attr_t attr;
    pthread_attr_init(&attr);

    cpu_set_t cpuset;
    CPU_ZERO(&cpuset);
    CPU_SET(g_config.monitor_cpu, &cpuset);
    pthread_attr_setaffinity_np(&attr, sizeof(cpuset), &cpuset);

    /* Use real_pthread_create to avoid registering monitor thread */
    int ret = real_pthread_create(&g_monitor.monitor_tid, &attr,
                                   monitor_thread_func, NULL);
    pthread_attr_destroy(&attr);

    if (ret != 0) {
        TM_ERR("Failed to create monitor thread: %s", strerror(ret));
        return -1;
    }

    pthread_setname_np(g_monitor.monitor_tid, "tm:monitor");

    TM_DBG("Monitor thread launched");
    return 0;
}

void monitor_cleanup(void)
{
    cleanup_pebs_allload_events();
    cleanup_pebs_events();
    cleanup_pebs_store_events();
    cleanup_ocr_events();
    cleanup_imc_events();
    congest_ctrl_cleanup();

    TM_DBG("Monitor cleaned up");
}

/* ══════════════════════════════════════════════════════════════════════
 * Multi-process follower thread
 *
 * Runs in non-leader processes. Waits for the leader to signal
 * PHASE_MIGRATING, then pauses own threads, migrates own objects,
 * and waits for PHASE_DONE before resuming.
 * ══════════════════════════════════════════════════════════════════════ */

static pthread_t g_follower_tid;
static volatile bool g_follower_running = false;

static void *epoch_follower_thread_func(void *arg)
{
    (void)arg;

    pid_t my_tid = (pid_t)syscall(SYS_gettid);
    TM_DBG("Epoch follower thread started (tid=%d)", my_tid);

    struct timespec ocr_ts;
    ocr_ts.tv_sec  = g_config.ocr_interval_ms / 1000;
    ocr_ts.tv_nsec = (g_config.ocr_interval_ms % 1000) * 1000000L;

    while (g_follower_running) {
        epoch_sync_t *es = shm_epoch_sync();
        if (!es) break;

        /* During PHASE_SAMPLING: periodically read own OCR counters
         * and accumulate into shared memory for the leader to collect. */
        int phase = atomic_load_explicit(&es->phase, memory_order_acquire);
        while (phase != PHASE_MIGRATING && g_follower_running) {
            nanosleep(&ocr_ts, NULL);
            ocr_self_read_to_shm();
            phase = atomic_load_explicit(&es->phase, memory_order_acquire);
        }

        if (!g_follower_running) break;

        /* Final OCR read before migration */
        ocr_self_read_to_shm();

        /* Migrate our own objects: controller interleave if the leader's
         * decision owns this epoch, else the base bandwidth path. The
         * cc_* fields were published before the leader set PHASE_MIGRATING, so
         * the acquire-load on phase above makes them visible here. */
        if (atomic_load_explicit(&es->cc_owns, memory_order_acquire))
            congest_ctrl_migrate_local(
                atomic_load_explicit(&es->cc_r, memory_order_acquire),
                atomic_load_explicit(&es->cc_density_max, memory_order_acquire),
                atomic_load_explicit(&es->cc_g, memory_order_acquire), false);
        else
            migrate_execute_own_pending();

        /* Signal that we're done */
        atomic_fetch_add_explicit(&es->migrate_done, 1, memory_order_release);
        atomic_fetch_add_explicit(&es->futex_word, 1, memory_order_release);
        shm_futex_wake(&es->futex_word, INT_MAX);

        /* Wait for PHASE_DONE (or PHASE_SAMPLING for next epoch) */
        phase = atomic_load_explicit(&es->phase, memory_order_acquire);
        while (phase == PHASE_MIGRATING && g_follower_running) {
            int fw = atomic_load_explicit(&es->futex_word,
                                          memory_order_acquire);
            shm_futex_wait(&es->futex_word, fw);
            phase = atomic_load_explicit(&es->phase, memory_order_acquire);
        }

        /* Wait briefly for PHASE_SAMPLING to be set (leader resets after DONE) */
        while (phase == PHASE_DONE && g_follower_running) {
            struct timespec ts = { .tv_sec = 0, .tv_nsec = 1000000 }; /* 1ms */
            nanosleep(&ts, NULL);
            phase = atomic_load_explicit(&es->phase, memory_order_acquire);
        }
    }

    TM_DBG("Epoch follower thread exiting");
    return NULL;
}

int epoch_follower_launch(void)
{
    g_follower_running = true;

    int ret = real_pthread_create(&g_follower_tid, NULL,
                                   epoch_follower_thread_func, NULL);
    if (ret != 0) {
        TM_ERR("Failed to create follower thread: %s", strerror(ret));
        return -1;
    }

    pthread_setname_np(g_follower_tid, "tm:follower");
    TM_DBG("Epoch follower thread launched");
    return 0;
}

void epoch_follower_stop(void)
{
    g_follower_running = false;

    /* Wake the follower if it's stuck waiting */
    epoch_sync_t *es = shm_epoch_sync();
    if (es) {
        atomic_fetch_add_explicit(&es->futex_word, 1, memory_order_release);
        shm_futex_wake(&es->futex_word, INT_MAX);
    }

    pthread_join(g_follower_tid, NULL);
    TM_DBG("Epoch follower stopped");
}
